version: "3.9"
services:
  db:
    image: postgres
    container_name: 'db'
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - dev.env
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", $POSTGRES_DB, "-U", $POSTGRES_USER ]
      timeout: 3s
      retries: 20
    networks:
      - mainnetwork

  redis:
    image: redis
    restart: always
    networks:
      - mainnetwork


  web:
    build: .
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - dev.env
    networks:
      - mainnetwork
    command: python start.py

  worker:
    build: .
    restart: always
    depends_on:
      - web
    env_file:
      - dev.env
    networks:
      - mainnetwork
    command: ['celery', '-A', 'ClerkFoodhub', 'worker']

  beats:
    build: .
    restart: always
    depends_on:
      - web
    env_file:
      - dev.env
    networks:
      - mainnetwork
    command: ['celery', '-A', 'ClerkFoodhub', 'beat', '-l', 'info']

networks:
  mainnetwork:
    name: "mainnetwork"