version: "3.9"
services:
  db_clerk:
    image: postgres
    container_name: 'db_clerk'
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_USER: $DB_USER
      POSTGRES_DB: $DB_NAME
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", $DB_NAME, "-U", $DB_USER ]
      timeout: 3s
      retries: 5
    networks:
      - local_network

  redis:
    image: redis
    restart: always
    networks:
      - local_network


  clerkfoodhub:
    build: .
    restart: on-failure
    depends_on:
      db_clerk:
        condition: service_healthy
    volumes:
      - .:/code
#    ports:
#      - "8000:8000"
    env_file:
      - dev.env
    networks:
      - local_network
      - mainnetwork
    command: python start.py

  worker:
    build: .
    restart: always
    depends_on:
      - clerkfoodhub
    env_file:
      - dev.env
    networks:
      - local_network
    command: ['celery', '-A', 'ClerkFoodhub', 'worker']

  beats:
    build: .
    restart: always
    depends_on:
      - clerkfoodhub
    env_file:
      - dev.env
    networks:
      - local_network
    command: ['celery', '-A', 'ClerkFoodhub', 'beat', '-l', 'info']

networks:
  local_network:
    driver: bridge
    internal: true
  mainnetwork:
    external: true